#!/bin/sh
echo "$1"
if [ -d "$1" ];
then
	echo "Is a directory"
	for entry in "$1"/*
	do
		count=`grep "$entry" /home/pi/.omxplayer -c`
		if [ "$count" -eq "0" ];
		then
        		omxplayer "$entry"
        		xrefresh -display :0
        		echo "$entry\t`date +%d%m`" >> /home/pi/.omxplayer
		fi
	done
else
	echo "Not a directory"
fi
